<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Google\Auth\Credentials\ServiceAccountCredentials;

class FirebaseService
{
    /**
     * Generate a password reset link for a given email.
     * Uses the Identity Toolkit API with a Service Account token.
     * Returns the complete oobLink generated by Firebase.
     */
    public function generatePasswordResetLink(string $email)
    {
        try {
            $accessToken = $this->getAccessToken();
            if (!$accessToken) {
                throw new \Exception("Failed to get Firebase Access Token using google/auth");
            }

            $projectId = 'watered-c14bb';
            $response = Http::withToken($accessToken)
                ->post("https://identitytoolkit.googleapis.com/v1/projects/{$projectId}/accounts:sendOobCode", [
                    'requestType' => 'PASSWORD_RESET',
                    'email' => $email,
                    'returnOobLink' => true,
                ]);

            if ($response->failed()) {
                Log::error("Firebase OOB Link generation failed with status " . $response->status() . ": " . $response->body());
                return null;
            }

            Log::info("Firebase OOB Link generated successfully for: " . $email);
            return $response->json('oobLink');
        } catch (\Exception $e) {
            Log::error("FirebaseService Error in generatePasswordResetLink: " . $e->getMessage());
            return null;
        }
    }

    /**
     * Generate an OAuth2 access token using the official google/auth library.
     */
    protected function getAccessToken()
    {
        try {
            Log::info("Attempting to get Firebase Access Token via google/auth...");
            $serviceAccountFile = base_path('watered-c14bb-firebase-adminsdk-fbsvc-cf02191074.json');

            if (!file_exists($serviceAccountFile)) {
                Log::error("Firebase Service Account file not found at: " . $serviceAccountFile);
                return null;
            }

            $scopes = ['https://www.googleapis.com/auth/identitytoolkit'];
            $creds = new ServiceAccountCredentials($scopes, $serviceAccountFile);

            $tokenObj = $creds->fetchAuthToken();
            $token = $tokenObj['access_token'] ?? null;

            if ($token) {
                Log::info("Firebase Access Token successfully retrieved via google/auth.");
                return $token;
            } else {
                Log::error("google/auth did not return an access_token");
                return null;
            }
        } catch (\Exception $e) {
            Log::error("Failed to fetch Firebase token: " . $e->getMessage());
            return null;
        }
    }
}
